before:
  hooks:
    - go mod tidy

builds:
  - id: mcp-injector
    dir: ./cmd/mcp-injector
    main: .
    binary: mcp-injector
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'

sboms:
  - artifacts: archive

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
